### ISSUE TITLE
CSS Regression: header in cheatsheet is black on grey and hard to read

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1125]
See https://angular.io/docs/ts/latest/cheatsheet.html

![image](https://cloud.githubusercontent.com/assets/2286589/14664655/b28eb2c4-0681-11e6-84e0-d82487c31639.png)

**Comment by ericjim** [comment]
This might be the culprit

```css
.docs-content code {
  font-size: 14px;
   color: #1a2326;
}
```
